### ISSUE TITLE
FILE_MAP 需要完善

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/jupyter-echarts#13]
![image](https://user-images.githubusercontent.com/19553554/44837333-f1064c00-ac6b-11e8-8976-6712c62c012d.png)

FILE_MAP 需要完善，不然 online() 找不到本库对应的 js 文件。

**Comment by chfw** [comment]
点解？

**Comment by chenjiandongx** [comment]
不好意思，我的失误，跟你那个提的漏洞一样，我写成了 ONLINE_ASSETS 而不是 ONLINE_ASSETS_JS 所以导致文件没找到
